[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "quirk"
version = "0.1.0"
dependencies = ["typer"]
# optional fields like description, authors, etc.

[project.scripts]
quirk = "quirk.cli:app"

